### ISSUE TITLE
Spalten Editieren Bug

### ISSUE THREAD

**Issue by nimueller** [NRankedDev/JavaMyAdmin#45]
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'CHARAKTER_MAXIMUM_LENGTH' in 'field list'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.Util.getInstance(Util.java:387)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504)
    at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370)
    at javaMyAdmin.db.Table.getColumnInfo(Table.java:176)
    at javaMyAdmin.db.Table.getLength(Table.java:77)
    at javaMyAdmin.ui.dialogs.DialogEditTable.initGrid(DialogEditTable.java:66)
    at javaMyAdmin.ui.dialogs.util.OptionDialog.init(OptionDialog.java:110)
    at javaMyAdmin.ui.dialogs.util.DialogDynamicRows.init(DialogDynamicRows.java:59)
    at javaMyAdmin.ui.dialogs.util.OptionDialog.show(OptionDialog.java:93)
`

Da is iwo anstatt einem CHARACTER ein CHARAKTER mit k

**Comment by Normynator** [comment]
Fixed in e8cf0cc3f5dc3e77d211d281fa3bedbc18d73dc7

**Comment by Normynator** [comment]
@LegendSalocin 
Wenn ich Spalten editieren will ist bei mir alles ausgegraut, absicht?

**Comment by nimueller** [comment]
@Normynator 
Ja das soll so. Bereits existierende Spalten soll man ja nicht editieren können (außer dem Namen).
Hab das momentan noch nicht eingebaut, dass die wieder aktiviert sind, wenn man ne Spalte hinzufügt.
